dogmatiq/infix

- persistence/memory/doc.go
- persistence/memory/gingko_test.go
- persistence/memory/stream.go
- persistence/memory/stream_test.go
This PR adds an in-memory implementation of the `persistence.Stream`.
I'm going to try to keep an in-memory persistence layer in Infix, since it is designed for embedding in single-binary apps. This would replace any use-case we might have for using the testkit engine for anything outside of actual tests. (And it will be properly concurrent, unlike testkit).
> Implement in-memory stream.

- envelope/boundpacker.go
- envelope/boundpacker_test.go
- envelope/packer.go
- envelope/packer_test.go
A bound packer is a `Packer` that is bound to specific parent message and handler. It validates that any new envelopes contain messages intended to be produced by that handler.
> Implement `envelope.BoundPacker`.

- persistence/provider/sql/driver.go
- persistence/provider/sql/mysql/driver.go
- persistence/provider/sql/postgres/driver.go
- persistence/provider/sql/postgres/error.go
- persistence/provider/sql/sqlite/driver.go
- persistence/provider/sql/transaction.go
> Convert PosgreSQL "query_canceled" errors into context errors.

- persistence/internal/providertest/queue.go
- persistence/provider/boltdb/queue.go
- persistence/provider/memory/queue.go
- persistence/provider/sql/mysql/queue.go
- persistence/provider/sql/postgres/error.go
- persistence/provider/sql/postgres/queue.go
- persistence/provider/sql/queue.go
- persistence/provider/sql/sqlite/queue.go
- persistence/subsystem/queue/transaction.go
This PR changes the `AddMessagesToQueue()` methods into the singular `AddMessageToQueue()` and requires the user to supply the time of the next (first) time that the message should be attempted.
This allows us to avoid unmarshaling previously marshaled data to determine the correct time to use.
> Accept "next attempt" time directly when enqueuing messages.

- envelope/marshaling.go
- envelope/marshaling_test.go
- eventstream/eventstore_test.go
- persistence/internal/providertest/datastore.go
- persistence/internal/providertest/eventstore.go
- persistence/internal/providertest/transaction.go
- persistence/provider/boltdb/database_test.go
- persistence/provider/boltdb/eventstore.go
- persistence/provider/memory/eventstore.go
- persistence/provider/sql/eventstore.go
- persistence/provider/sql/mysql/eventstore.go
- persistence/provider/sql/mysql/schema.go
- persistence/provider/sql/postgres/error.go
- persistence/provider/sql/postgres/eventstore.go
- persistence/provider/sql/postgres/schema.go
- persistence/provider/sql/sqlite/eventstore.go
- persistence/provider/sql/sqlite/schema.go
- persistence/subsystem/eventstore/transaction.go
This allows us to have a more meaningful signature, as the function now returns offset of the saved event, rather than the offset after the saved events.
> Replace `SaveEvents()` with the singular `SaveEvent()`.

- app.go
- cmd/bank/main.go
- cmd/bank/ui/input.go
- cmd/bank/ui/log.go
- cmd/bank/ui/output.go
- cmd/bank/ui/ui.go
- draftspecs/messagingspec/error.pb.go
- draftspecs/messagingspec/error.proto
- engine.go
- engine_test.go
- eventstream.go
- eventstream/networkserver_test.go
- network.go
- persistence/provider/sql/driver_test.go
- queue/doc.go
- queue/ginkgo_test.go
- queue/queue.go
- queue/queue_test.go
This PR adds the `ExecuteCommand()` method to `Engine`, meaning that it now implements `dogma.CommandExecutor`.
I've also started to add a basic CLI app like Koden's one in dogmatiq/example. I tried to use his as is but it relies on the fact that the test engine is synchronous.
> Command executor.

- app.go
- engine.go
- fixtures/envelope.go
- queue/consumer_test.go
- queue/executor.go
- queue/executor_test.go
- queue/queue.go
- queue/queue_test.go
- queue/session_test.go
We need to be able to track messages in the `queue.Queue` that are persisted as part of a transaction that was created while handling an event from a stream (that is, not a message from the queue).
This PR also fixes #113 (see dadac05).
> Separate session from queue.

- app.go
- envelope/packer.go
- envelope/packer_test.go
- fixtures/envelope.go
- internal/x/gomegax/panicwith.go
Fixes #137 
I've gone to some length to ensure the panic messages here are fairly straightforward, as users will see these panics if they execute/record the wrong messages via the various scope interfaces.
> Improve error messages from envelope packer.

- handler/integration/scope.go
- handler/integration/sink_test.go
- internal/mlog/icon.go
- internal/mlog/log.go
- internal/mlog/log_test.go
- internal/mlog/write_test.go
- pipeline/ack.go
- pipeline/ack_test.go
Fixes #131 
This PR adds logging of messages that are produced by integration handlers.
The logging occurs immediately, so if the transaction is latter rolled back you can still see that the handler recorded them, but you have to ensure there's no error latter in the log. 
I've also changed the `Acknowledger` to always log when a message comes in, not only when it's acknowledged. This puts the log messages in the correct order, with the "cause" showing before the "effect".
As best I can tell, this behavior is the same as Ax.
> Log produced messages.

- app.go
- handler/aggregate/pipeline.go
- handler/aggregate/pipeline_test.go
- handler/cache/cache.go
- handler/cache/cache_test.go
- handler/cache/doc.go
- handler/cache/ginkgo_test.go
- handler/cache/record.go
- handler/cache/record_test.go
- internal/x/syncx/mutex.go
- internal/x/syncx/mutex_test.go
Fixes #185
This PR introduces a highly-use-case-specific cache to the `aggregate.Sink`. Each handler has its own cache instance, and each record in the cache represents an aggregate instance.
Records are "acquired" from the cache, locking them so that no other goroutine can acquire them at the same time. This ensures that only one goroutine handles a message for a given instance at a time, reducing the likelihood of OCC failures without any IO. (This approach made #187 redundant, which is why I closed it).
When a cache record has been acquired, the acquirer must explicitly call a `KeepAlive()` method in order to retain that record in the cache when it's released. This approach feels a little unusual to me, but seems to work well in practice because it automatically invalidates the cache …
> Implement an in-memory cache of aggregate instances.

- eventstream/internal/streamtest/suite.go
- eventstream/networkstream/server.go
- eventstream/persistedstream/stream.go
This PR fixes an issue shared by both `persistencestream.Stream` and `networkstream.server` whereby the `MinOffset` used to query the event store was not being incremented after reading an event, resulting in repeatedly returning the same event from the cursor after reaching the end of the persisted events the first time.
This initially went unnoticed because the only place the stream was used was to populate projections, which would immediately retry by opening the cursor at the next offset. An error was logged but the projection content was correct.
Fixes #194
> Correctly increment offset in persistencedstream.

- eventstream/networkstream/server_test.go
- pipeline/queue/queue.go
- pipeline/queue/queue_test.go
- pipeline/queue/request_test.go
Fixes #188.
- Add test for `eventstore.Result.Next()` failure in `networkstream.server`
- Add test to ensure `Queue.Track()` does not block once `queue.Run()` has returned
- Add test to ensure `Request.Close()` does not block once `queue.Run()` has returned
> Fix flapping test coverage.

- app.go
- handler/aggregate/pipeline.go
- handler/aggregate/pipeline_test.go
- handler/integration/pipeline.go
Fixes #191 
Note that aggregate handlers themselves don't accept a context because they are pure functions. 
This timeout applies to the `cache.Acquire()` and `loader.Load()` operations.
> Add a timeout to aggregate cache acquire/load operation.

- eventstream/internal/streamtest/suite.go
- eventstream/networkstream/server.go
- eventstream/networkstream/server_test.go
- eventstream/persistedstream/stream.go
Fixes #194.
This PR corrects PR #197 which provided a insufficent fix to #194.
> Ensure stream events are not duplicated when the first offset is filtered out.

- persistence/internal/providertest/eventstore/repository.go
- persistence/provider/boltdb/eventstore.go
- persistence/provider/memory/eventstore.go
- persistence/provider/sql/eventstore.go
- persistence/provider/sql/mysql/eventstore.go
- persistence/provider/sql/postgres/error.go
- persistence/provider/sql/postgres/eventstore.go
- persistence/provider/sql/sqlite/eventstore.go
- persistence/subsystem/eventstore/repository.go
This PR adds the `eventstore.Repository.NextEventOffset()` method, which returns the next "unused" offset in the store.
One use for this will be used when one application discovers another and wants to start consuming events that "happen from  now on", rather than from offset `0`, which will be the case for processes. 
This probably wouldn't have been done until the 0.2.0 "multiple apps" milestone, except that it will also be useful for #74 to prime the buffer with recent events even after a cold start.
It's naturally racy, insofar as the store could have an event persisted to it the moment you get the result, but that is adequate for these use cases.
> Add method for getting the next free offset from the event store.

- pipeline/observe.go
- pipeline/observe_test.go
- pipeline/queue/pipeline.go
- pipeline/queue/pipeline_test.go
- pipeline/response.go
- pipeline/response_test.go
This PR removes these two container types, as they had a tendency to cause coupling to the `pipeline` package when there really needn't be any.
These types contained a `*parcel.Parcel` and the `*[queue|event]store.Item`. Instead I've changed the pipeline observers to pass two separate slices of parcels and items to the observers.
This not only removes this extra type and hence the coupling, but also means that observers that don't care about one of the representations (parcel, or item) don't have to iterate through to extract the value they do care about from the container type.
> Remove `EnqueuedCommand` and `RecordedEvent`.

- eventstream/networkstream/server.go
- eventstream/networkstream/server_test.go
- eventstream/networkstream/stream_test.go
- network.go
This change essentially reverts #75 by returning to serving events from a stream, rather than reading from a store (though the overall structure of the server remains much better) than it was before #75.
Once #233 and #230 are merged, the network server can use the `persistedstream` as the source of it's messages, and that will take care of shifting between reading from the store and the in memory cache.
> Change `networkstream.server` source messages from a stream.

- app.go
- engine.go
- eventstream/persistedstream/cursor.go
- eventstream/persistedstream/stream.go
- eventstream/persistedstream/stream_test.go
- network.go
- pipeline/eventstream.go
- pipeline/eventstream_test.go
- pipeline/queue.go
Blocked by #217, fixes #74
This PR changes `persistedstream.Stream` to use a `memorystream.Stream` as a cache of recent events.
`persistedstream.cursor` now hits this cache first, falling back to query an `eventstore.Repository` if the required offset is too old to be in the cache.  
Once the cursor "runs out" of events in the store, in other words, it has caught up to the tail of the stream, it tries to "lock onto" the memory stream again, using it exclusively from then on.
> Use memory stream as a cache of recent events.

- eventstream/networkstream/marshaler.go
- eventstream/networkstream/marshaler_test.go
- network.go
Fixes #74 - last part!
This PR adds a `NoopUnmarshaler` which decorates a `marshalkit.Marshaler` in order to make the `Unmarshal()` method do nothing.
It's used to construct a `persistedstream.Stream` instance that can be used by `networkstream.server` to get events to serve without the overhead of unmarshaling them.  The unmarshaling is useless is because all the network server does is sends the marshaled-form in a gRPC response.
> Avoid unmarshaling messages in the network server.

- eventstream/persistedstream/stream_test.go
- fixtures/persistence.go
- fixtures/pipeline.go
- handler/aggregate/loader_test.go
- persistence/internal/providertest/aggregatestore/transaction.go
- persistence/internal/providertest/aggregatestore/util.go
- persistence/internal/providertest/datastore.go
- persistence/internal/providertest/eventstore/transaction.go
- persistence/internal/providertest/eventstore/util.go
- persistence/internal/providertest/offsetstore/transaction.go
- persistence/internal/providertest/offsetstore/util.go
- persistence/internal/providertest/queuestore/transaction.go
- persistence/internal/providertest/queuestore/util.go
- persistence/internal/providertest/transaction.go
- persistence/provider/boltdb/eventstore.go
- persistence/provider/boltdb/transaction.go
- persistence/provider/memory/eventstore.go
- persistence/provider/memory/transaction.go
- persistence/provider/sql/eventstore.go
- persistence/provider/sql/transaction.go
- persistence/transaction.go
- persistence/transaction_test.go
- pipeline/queue_test.go
- queue/executor.go
- queue/queue_test.go
- queue/request.go
- queue/request_test.go
This PR adds `persistence.TransactionResult` type returned by `persistence.Transaction.Commit()` method. This type is the container for all committed event for the committed event and queue items that looks like the following:
```go
// TransactionResult is the result returned by Transaction.Commit() method.
type TransactionResult struct {
EventItems []*eventstore.Item
QueueItems []*queuestore.Item
}
```
> Add `TransactionResult` type.

- pipeline/queue.go
- pipeline/queue_test.go
- queue/executor.go
- queue/message.go
- queue/queue.go
- queue/queue_test.go
- queue/request_test.go
This PR changes `Queue.Track()` so that it cannot timeout or return an error.
Either the message is added to the tracking queue, or the "non-exhaustive" flag is set so that the queue knows it doesn't have everything in memory.
> Do not require context to call `Queue.Track()`.

- fixtures/eventstore.go
- persistence/internal/providertest/eventstore/repository.go
- persistence/internal/providertest/eventstore/util.go
- persistence/provider/boltdb/eventstore.go
- persistence/provider/memory/eventstore.go
- persistence/provider/sql/eventstore.go
- persistence/provider/sql/mysql/eventstore.go
- persistence/provider/sql/mysql/schema.go
- persistence/provider/sql/postgres/error.go
- persistence/provider/sql/postgres/eventstore.go
- persistence/provider/sql/postgres/schema.go
- persistence/provider/sql/sqlite/eventstore.go
- persistence/provider/sql/sqlite/schema.go
- persistence/subsystem/eventstore/repository.go
- persistence/subsystem/eventstore/repository_test.go
This PR partially addresses #220 by adding `LoadEventsBySource()` method to `eventstore.Repository` and modifying the implementations of `eventstore.Transaction.SaveEvent()` method to persist message ID in a separate field (if not doing that already) so that `eventstore.Repository.LoadEventsForAggregate()` method can load source events from the given message ID.
> Add LoadEventsBySource() method in eventstore.Repository

- handler/entrypoint_test.go
- handler/unitofwork.go
- persistence/internal/providertest/eventop.go
- persistence/persister.go
- persistence/provider/boltdb/eventstore.go
- persistence/provider/memory/eventstore.go
- persistence/provider/memory/transaction.go
- persistence/provider/sql/eventstore.go
- persistence/transaction_test.go
As it turns out there's nowhere that we actually need the eventstore items directly, so in the interest of simplicity and the whole "keeping the persistence layer dumb" idea, I've replaced the items in the result with a map of message ID to offset.
> Replace `persistence.Result.EventStoreItems` with `EventOffsets`.

- handler/queue.go
- queue/queue.go
- queue/queue_test.go
This PR simplifies the internals of `queue.Queue` making it easier to add additional operations that manipulate the messages on the queue.
> Simplify `queue.Queue` internals and naming.

- app.go
- fixtures/handler.go
- handler/cache/cache.go
- handler/entrypoint.go
- handler/entrypoint_test.go
- handler/queue_test.go
- handler/unitofwork.go
This PR replaces the concept of "unit of work observers" with "deferred functions", similar to Go's `defer` keyword. The upshot of this is that the unit-of-work now provides guarantees about the order in which the functions will be called.
This was added to allow precise control over what code is executed while aggregate and process cache records are still held..
> Replace `UnitOfWork.Observe()` with `Defer()`.

- handler/aggregate/adaptor_test.go
- handler/aggregate/scope.go
See also https://github.com/dogmatiq/dogma/issues/116
> Disallow recreation of an aggregate instance during the same message by which it is destroyed.

- handler/aggregate/adaptor.go
- handler/aggregate/adaptor_test.go
- handler/aggregate/scope.go
This PR updates testkit to allow the behavior documented in [ADR-17](https://github.com/dogmatiq/dogma/blob/master/docs/adr/0017-recreate-aggregate-after-destruction.md).
> Allow AggregateCommandScope.Destroy() and RecordEvent() to be called in any order.
